services:
  bnovo-todo:
    build:
      context: .
      dockerfile: Dockerfile
    image: bnovo-todo
    container_name: bnovo-todo
    restart: unless-stopped
    ports:
      - '5173:5173'
    volumes:
      - .:/usr/src/client:rw